# Generated by Django 5.0.6 on 2025-04-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0002_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="recipient",
            field=models.CharField(
                help_text="Recipient's email, phone number, or device ID",
                max_length=255,
            ),
        ),
    ]
